CREATE OR REPLACE TABLE STAGE.CASES AS
SELECT
  CASE_ID,
  COALESCE(REGION, 'Unknown') AS REGION,
  ALERT_TYPE,
  OPEN_DATE,
  CLOSE_DATE,
  ASSIGNED_ANALYST,
  CASE_STATUS,
  DATEDIFF('day', OPEN_DATE, CLOSE_DATE) AS SLA_DAYS
FROM RAW.CASES;