-- SLA Validation
SELECT * FROM CURATED.CASE_SLA WHERE SLA_DAYS < 0;

-- Null Region Check
SELECT * FROM CURATED.CASE_SLA WHERE REGION IS NULL OR REGION = 'Unknown';

-- Alert Type Validation
SELECT DISTINCT ALERT_TYPE FROM CURATED.CASE_VOLUME
MINUS
SELECT ALERT_TYPE FROM STAGE.ALERT_TYPES;